### ISSUE TITLE
Version of numpy

### ISSUE THREAD

**Issue by schnapper79** [RulinShao/retrieval-scaling#4]
I tried to follow the quickstart. Obviously there is a problem with faiss and numpy. 

```
Traceback (most recent call last):  File "/workspace/retrieval-scaling/ric/main_ric.py", line 8, in <module>
    from src.index import build_index
  File "/workspace/retrieval-scaling/src/index.py", line 21, in <module>
    import faiss
  File "/root/miniconda3/envs/scaling/lib/python3.11/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/root/miniconda3/envs/scaling/lib/python3.11/site-packages/faiss/loader.py", line 98, in <module>
    from .swigfaiss import *
  File "/root/miniconda3/envs/scaling/lib/python3.11/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
Traceback (most recent call last):
  File "/root/miniconda3/envs/scaling/lib/python3.11/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.


Traceback (most recent call last):
  File "/workspace/retrieval-scaling/ric/main_ric.py", line 8, in <module>
    from src.index import build_index
  File "/workspace/retrieval-scaling/src/index.py", line 21, in <module>
    import faiss
  File "/root/miniconda3/envs/scaling/lib/python3.11/site-packages/faiss/__init__.py", line 16, in <module>
    from .loader import *
  File "/root/miniconda3/envs/scaling/lib/python3.11/site-packages/faiss/loader.py", line 98, in <module>
    from .swigfaiss import *
  File "/root/miniconda3/envs/scaling/lib/python3.11/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: numpy.core.multiarray failed to import
```

I downgraded numpy to Version 1.23.5, which resolved the first error, but the second error with `ImportError: numpy.core.multiarray failed to import` remained

**Comment by RulinShao** [comment]
Hi! I was using `numpy==1.26.4`, would you like to try with this version?

**Comment by RulinShao** [comment]
Closing this issue, but let me know if you have further questions!
